# Generated by Django 5.0.14 on 2026-06-08 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_no', models.IntegerField()),
                ('trump_card', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BIDDING', 'Bidding'), ('PLAYING', 'Playing'), ('LOCKED', 'Locked'), ('SCORING', 'Scoring'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='matches.match')),
            ],
            options={
                'ordering': ['round_no'],
                'unique_together': {('match', 'round_no')},
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid', models.IntegerField()),
                ('is_blind', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='matches.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rounds.round')),
            ],
            options={
                'unique_together': {('round', 'player')},
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tricks_won', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='matches.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rounds.round')),
            ],
            options={
                'unique_together': {('round', 'player')},
            },
        ),
    ]
