# Generated by Django 5.0.14 on 2026-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='bids_locked',
            field=models.BooleanField(default=False),
        ),
    ]
