# Generated by Django 5.0.14 on 2026-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='trump_suit',
            field=models.CharField(default='Spades ♠', max_length=20),
        ),
    ]
