# Generated by Django 5.2.15 on 2026-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_trump_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
